### ISSUE TITLE
Hacktoberfest 2k20

### ISSUE THREAD

**Issue by rahulmishra11** [rahulmishra11/Algorithms#1]
**Algorithms in PYTHON**
Implement the algorithms in  python.
Kindly Read ,Below link!!
https://github.com/rahulmishra11/Algorithms/blob/master/CONTRIBUTING.md

**Comment by gillesigot** [comment]
Hello, could you assign me? I would like to add sorting algorithm in python.

**Comment by rahulmishra11** [comment]
> Hello, could you assign me? I would like to add sorting algorithm in python.

Yes you may proceed!

**Comment by anshika0207** [comment]
@rahulmishra11 can you assign this to me? I would like to add merge sort algorithm in Python

**Comment by VicodinAbuser** [comment]
@rahulmishra11  I would like to add code for the Selection Sort algorithm in Python. Can you assign me?

**Comment by rahulmishra11** [comment]
> @rahulmishra11 can you assign this to me? I would like to add merge sort algorithm in Python

Yes! Proceed.

**Comment by rahulmishra11** [comment]
> @rahulmishra11 can you assign this to me? I would like to add merge sort algorithm in Python

Yes! Proceed

**Comment by VicodinAbuser** [comment]
@rahulmishra11 I have made a PR adding the Selection Sort code in Python. Please check.

**Comment by Shinh18** [comment]
Hey @rahulmishra11 
I would like to implement Stack using linked list for C++. Please assign it to me.

**Comment by rahulmishra11** [comment]
> Hey @rahulmishra11
> I would like to implement Stack using linked list for C++. Please assign it to me.

Please Contribute in Python
